spring:
  mongodb:
    embedded:
      version: 4.0.12
  data:
    mongodb:
      uri: mongodb://localhost:27017/atlas_trade_control_test

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    com.gic: DEBUG

server:
  port: 0
