spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD:}

logging:
  level:
    root: WARN
    com.gic: INFO
  file:
    name: /var/log/trading-system/application.log
    max-size: 10MB
    max-history: 30

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: never
