spring.data.mongodb.uri=mongodb://localhost:27017/atlas_trade_control_test
spring.mongodb.embedded.version=4.0.12

spring.redis.host=localhost
spring.redis.port=6379

spring.cache.cache-names=instruments
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=3600s
